### ISSUE TITLE
The input element of mobile number and checkmark doesnt align to their respective boxes .

### ISSUE THREAD

**Issue by ImAnshuJoshi** [ConnectX-IIIT/connectx-frontend#1]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/101829944/194924363-e84c6a71-3269-4ea3-ad79-1567b31fc14a.png">
Hey , i would like to work on this issue , can you assign this to me ?

**Comment by RajVarsani** [comment]
Sure @ImAnshuJoshi 
Go ahead 🙌
